-- CreateEnum
CREATE TYPE "ActivityStatus" AS ENUM ('ONLINE', 'AWAY', 'BUSY', 'OFFLINE');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "activityStatus" "ActivityStatus" NOT NULL DEFAULT 'OFFLINE',
ADD COLUMN     "contentCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "followersCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "followingCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "isOnline" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "lastActivityAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "lastSeenAt" TIMESTAMP(3),
ADD COLUMN     "onlineStatusUpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
